# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170416_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
